name: Cache events

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull events from relays, then cache on Redis
        run: curl -s -X GET "https://nashboard.space/api/data/insert/events"
