name: Cache events

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull events from relays, then cache on Redis
        run: curl -s -X GET "https://rococo-belekoy-885436.netlify.app/api/data/insert/events"
