name: Cache monthly

on:
  schedule:
    - cron: "45 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull unique event count (one month) from relays, then cache on Redis
        run: curl -s -X GET "https://rococo-belekoy-885436.netlify.app/api/data/insert/monthly"
